#coding:utf-8

def reverse(seq):
    reverse = ""
    length = len(seq)
    for i in range(length):
        if seq[length-i-1] == "A" or seq[length-i-1] == "a":
            reverse += "T"
        elif seq[length-i-1] == "T" or seq[length-i-1] == "t":
            reverse += "A"
        elif seq[length-i-1] == "C" or seq[length-i-1] == "c":
            reverse += "G"
        elif seq[length-i-1] == "G" or seq[length-i-1] == "g":
            reverse += "C"
    return reverse

testseq = "ATGTCTAACTTTAAGAATTTTACTTTAAATTCCTTTGAAGATCATTACGGGAAGGCTCCTGAAATACCAAAGATAGAGGAAGAGAAATTGGAAGCAATAAACACAAATGCGTCTTCCTTGAAAAAGATACATAAAAGCAAAAGGGGCACCTCAAAATATGACCAAAAGAATGTATTTAGAAACTCAGTGACTGCTTTAGCGCAAGTACGGCCGCCAAAATCGGTAAAGATCATAGAGCAAAACATTGAATTCGCCAATCCGAGGAGCTTTGACCTCCTGCACTCCACAAATACTATCTGTTTCAATAAGAAAAGTGGTACTGCGGATATTAAGTCGAGTGTGGAATCTCAAAACTCCAGCGATGTTGATAACGATATGTTACATGTTGGAGGGTCTACGGACTTGGGAGGTAATAGTAATGATGACGCGGAAACAAAACAACTGAGGAAATTCCGATGGTCCAATAATGAAGAAAAAAGTCTTTGTGAAAAGCTGACAGTTATTTATTGGGCTCTTTTGCTCAATACAACGAAGAGAGCAAGTAAGAGGAGGCCGATTCTATGCCACCAGGTGATAGCTGAGTTTTTCAATAAAGTTTATAAAGAAAAATCAAGGGTGCCTATAACTTCGAGATATATCAGGGATAATCTTGTGAATTGGGTAATGCAGGGGAAGGAATTGAATGAAAAGGGTTGGATAGCTGATGTTAAATCCGGTGATCTACAAGAGCAATTCAATTTAGCAACTATCAAATTATATGAAAGTGCAGAAAGCAGACGCATCATCATGGGTAAAGACAAAGGTCCTAGAAAAGAAAGTATAGGAAATGACGGTTCAATACGTGCACAAGAAGAGTCTTGCTACGTGACAGGTAAAAAATCCCAGGTTCCAATAGAGAATAACTGGAAAGAAGACCATAGGGAGTCTATTAGGAATCAGATATTGGCTTTGAACCTGAATGATGAAGATTTTTTTCAAAATACCATTAATATCCTTTCTAGTATTGATGAACCAGAATTAAGACAGCATGTGGTCATGATCTTAGAACTGGTCAATATGGAAATAGATGACGGTAAAACAGTACGAGAGAAGCTCCGGGATGTAGAATTGAGTATTAACAGGCTGCAGGTCGATATGAAGGAAATAAAGGAAATGCTTCATACGCTATCAAACAAATGA"
print reverse(testseq)
